import { LitElement, html, nothing } from 'lit';
import { customElement, property, query, state } from 'lit/decorators.js';
import { modalStyles } from './styles.js';
import { helpIcon, arrowIcon, spinnerIcon, checkIcon, errorIcon, closeIcon } from './icons.js';
import type { ModalState } from '../types.js';

/**
 * Custom events dispatched by the modal:
 *   - `actioncode:submit`  — detail: { code: string }
 *   - `actioncode:cancel`  — (no detail)
 */

const TAG_NAME = 'actioncode-modal';

@customElement(TAG_NAME)
export class ActionCodeModal extends LitElement {
    static override styles = modalStyles;

    /* --- Public reactive properties (set by adapter) --- */

    @property({ reflect: true })
    theme: 'auto' | 'light' | 'dark' = 'auto';

    @property()
    modalState: ModalState = 'input';

    @property()
    message = '';

    @property()
    error = '';

    /* --- Internal state --- */

    @state()
    private _code = '';

    @state()
    private _showTooltip = false;

    @query('.code-input')
    private _input!: HTMLInputElement | null;

    /* --- Lifecycle --- */

    override connectedCallback(): void {
        super.connectedCallback();
        // Focus trap — prevent scrolling behind modal
        document.body.style.overflow = 'hidden';
    }

    override disconnectedCallback(): void {
        super.disconnectedCallback();
        document.body.style.overflow = '';
    }

    override firstUpdated(): void {
        // Auto-focus the input when modal opens
        requestAnimationFrame(() => this._input?.focus());
    }

    /* --- Render --- */

    override render() {
        return html`
            <div class="overlay" @click=${this._onCancel}></div>
            <div class="modal" @click=${(e: Event) => e.stopPropagation()}>
                <div class="header">
                    <h2 class="title">Action Codes</h2>
                    <button class="close-btn" @click=${this._onCancel} aria-label="Close">
                        ${closeIcon}
                    </button>
                </div>
                ${this._renderBody()}
            </div>
        `;
    }

    private _renderBody() {
        switch (this.modalState) {
            case 'input':
                return this._renderInput();
            case 'resolving':
                return this._renderStatus(spinnerIcon, '', this.message || 'Resolving code\u2026');
            case 'approve':
                return this._renderStatus(spinnerIcon, '', this.message || 'Approve in wallet\u2026');
            case 'success':
                return this._renderStatus(checkIcon, 'success', this.message || 'Done!');
            case 'error':
                return this._renderError();
            default:
                return nothing;
        }
    }

    private _renderInput() {
        return html`
            ${this._showTooltip ? html`
                <div class="tooltip">
                    An Action Code is a short, one-time code generated by a wallet.
                    Enter it here to sign transactions or messages remotely.
                    <a href="https://docs.actioncodes.org" target="_blank" rel="noopener">Learn more</a>
                </div>
            ` : nothing}
            <div class="input-row">
                <button
                    class="help-btn ${this._showTooltip ? 'active' : ''}"
                    @click=${this._onToggleTooltip}
                    aria-label="Help"
                >
                    ${helpIcon}
                </button>
                <input
                    class="code-input"
                    type="text"
                    inputmode="numeric"
                    placeholder="Enter code"
                    maxlength="24"
                    .value=${this._code}
                    @input=${this._onInput}
                    @keydown=${this._onKeydown}
                    autocomplete="off"
                    spellcheck="false"
                />
                <button
                    class="submit-btn"
                    @click=${this._onSubmit}
                    ?disabled=${!this._isValidCode()}
                    aria-label="Submit"
                >
                    ${arrowIcon}
                </button>
            </div>
            ${this.error ? html`<div class="error-text">${this.error}</div>` : nothing}
        `;
    }

    private _renderStatus(icon: unknown, variant: string, msg: string) {
        return html`
            <div class="status">
                <div class="status-icon ${variant}">${icon}</div>
                <div class="status-message">${msg}</div>
            </div>
        `;
    }

    private _renderError() {
        return html`
            <div class="status">
                <div class="status-icon error">${errorIcon}</div>
                <div class="status-message">${this.error || 'Something went wrong'}</div>
            </div>
        `;
    }

    /* --- Validation --- */

    private _isValidCode(): boolean {
        const trimmed = this._code.trim();
        return trimmed.length >= 6 && /^[a-zA-Z0-9]+$/.test(trimmed);
    }

    /* --- Event handlers --- */

    private _onInput(e: Event) {
        this._code = (e.target as HTMLInputElement).value;
        // Clear previous error when user types
        if (this.error) {
            this.error = '';
        }
    }

    private _onKeydown(e: KeyboardEvent) {
        if (e.key === 'Enter' && this._isValidCode()) {
            this._onSubmit();
        } else if (e.key === 'Escape') {
            this._onCancel();
        }
    }

    private _onSubmit() {
        if (!this._isValidCode()) return;
        this.dispatchEvent(new CustomEvent('actioncode:submit', {
            detail: { code: this._code.trim() },
            bubbles: true,
            composed: true,
        }));
    }

    private _onCancel() {
        this.dispatchEvent(new CustomEvent('actioncode:cancel', {
            bubbles: true,
            composed: true,
        }));
    }

    private _onToggleTooltip() {
        this._showTooltip = !this._showTooltip;
    }

    /* --- Public API for the adapter --- */

    /** Reset modal to input state */
    reset() {
        this.modalState = 'input';
        this.message = '';
        this.error = '';
        this._code = '';
        this._showTooltip = false;
    }

    /** Update modal state from adapter */
    setState(state: ModalState, message?: string, error?: string) {
        this.modalState = state;
        if (message !== undefined) this.message = message;
        if (error !== undefined) this.error = error;
    }
}

/* --- DOM helpers used by the adapter --- */

export function createModal(theme: 'auto' | 'light' | 'dark' = 'auto'): ActionCodeModal {
    const modal = document.createElement(TAG_NAME) as ActionCodeModal;
    modal.theme = theme;
    document.body.appendChild(modal);
    return modal;
}

export function destroyModal(modal: ActionCodeModal | null): void {
    if (modal && modal.parentNode) {
        modal.parentNode.removeChild(modal);
    }
}

declare global {
    interface HTMLElementTagNameMap {
        [TAG_NAME]: ActionCodeModal;
    }
}
